spring:
  rabbitmq:
    host: puffin.rmq2.cloudamqp.com
    port: 5672
    username: jimdppcw
    password: Iphj78xtvO-qxvMo5s1tqjt1rD4VwdSW
    virtual-host: jimdppcw

  redis:
    timeout: 500s
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 60000

  
  dataSource:
    username: vssfedixieyobl
    password: 87d52668b02ef63098afbbaef6ebbf03090bbbf0abf35f42439cd4a5eefce8b8
    url: jdbc:postgresql://ec2-34-194-40-194.compute-1.amazonaws.com:5432/d75l62ha0uc0n2
    driverClassName: org.postgresql.Driver
    
# spring.datasource.driver-class-name=org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        formar-sql : true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update



#  myDb?createDatabaseIfNotExist=true