spring:
  rabbitmq:
    host: puffin.rmq2.cloudamqp.com
    port: 5672
    username: jimdppcw
    password: Iphj78xtvO-qxvMo5s1tqjt1rD4VwdSW
    virtual-host: jimdppcw

  redis:
    timeout: 500s
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 60000

  dataSource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sql6516875
    password: pMUdRKNUZN
    url: jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6516875

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



#  myDb?createDatabaseIfNotExist=true